"""Initial migration

Revision ID: bb1805b2b273
Revises: 
Create Date: 2025-01-19 00:56:19.085287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1805b2b273'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("SET FOREIGN_KEY_CHECKS=0")
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS pembelian")
    op.create_table('pembelian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal_faktur', sa.Date(), nullable=False),
    sa.Column('no_faktur', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('kode_barang', sa.String(length=50), nullable=False),
    sa.Column('nama_barang', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('harga_beli', sa.Float(), nullable=False),
    sa.Column('diskon', sa.Float(), nullable=False),
    sa.Column('pajak', sa.Float(), nullable=False),
    sa.Column('harga_jual', sa.Float(), nullable=False),
    sa.Column('exp_date', sa.Date(), nullable=False),
    sa.Column('hpp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_faktur')
    )
    op.execute("DROP TABLE IF EXISTS purchase_detail")
    op.execute("DROP TABLE IF EXISTS purchase")
    # ### end Alembic commands ###


    op.execute("SET FOREIGN_KEY_CHECKS=1")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS purchase")
    op.create_table('purchase',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('purchase_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payment_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name='purchase_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_pkey'),
    sa.UniqueConstraint('invoice_number', name='purchase_invoice_number_key'),
    postgresql_ignore_search_path=False
    )
    op.execute("DROP TABLE IF EXISTS purchase_detail")
    op.create_table('purchase_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('purchase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purchase_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['produk.id'], name='purchase_detail_product_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], name='purchase_detail_purchase_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_detail_pkey')
    )
    op.execute("DROP TABLE IF EXISTS pembelian")
    # ### end Alembic commands ###
